CREATE TABLE detalhes_tldos (
    codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    data DATETIME NOT NULL,
    SOPMixFor75 VARCHAR(20) NOT NULL,
    SOPEnxaugou3vezes VARCHAR(20) NOT NULL,
    SOPTemEPICompleto VARCHAR(20) NOT NULL,
    SOPPulvComBombaComCntFluxo VARCHAR(20) NOT NULL,
    todosPertencesForaCasa VARCHAR(20) NOT NULL,
    todosPertencesNTiradosCobertos VARCHAR(20) NOT NULL,
    existeVazamentoBomba VARCHAR(20) NOT NULL,
    SOPPulvComDist45cmParede VARCHAR(20) NOT NULL,
    SOPMantemVelocCorrecta VARCHAR(20) NOT NULL,
    existeSubreposicao5cm VARCHAR(20),
    SOPMixFor75Sim BIGINT(80),
    SOPMixFor75Nao BIGINT(80),
    SOPEnxaugou3vezesSim BIGINT(80),
    SOPEnxaugou3vezesNao BIGINT(80),
    SOPTemEPICompletoSim BIGINT(80),
    SOPTemEPICompletoNao BIGINT(80),
    SOPPulvComBombaComCntFluxoSim BIGINT(80),
    SOPPulvComBombaComCntFluxoNao BIGINT(80),
    todosPertencesForaCasaSim BIGINT(80),
    todosPertencesForaCasaNao BIGINT(80),
    todosPertencesNTiradosCobertosSim BIGINT(80),
    todosPertencesNTiradosCobertosNao BIGINT(80),
    existeVazamentoBombaSim BIGINT(80),
    existeVazamentoBombaNao BIGINT(80),
    SOPPulvComDist45cmParedeSim BIGINT(80),
    SOPPulvComDist45cmParedeNao BIGINT(80),
    SOPMantemVelocCorrectaSim BIGINT(80),
    SOPMantemVelocCorrectaNao BIGINT(80),
    existeSubreposicao5cmSim BIGINT(80),
    existeSubreposicao5cmNao BIGINT(80),
    codigo_tlOusupBrigada BIGINT(20) NOT NULL,
    codigo_bairro BIGINT(20) NOT NULL,
    codigo_roceador BIGINT(20) NOT NULL,
    FOREIGN KEY (codigo_roceador) REFERENCES actor(codigo),
    FOREIGN KEY (codigo_tlOusupBrigada) REFERENCES actor(codigo),
    FOREIGN KEY (codigo_bairro) REFERENCES bairro(codigo)
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
